### ISSUE TITLE
Error while adding this service into constructor

### ISSUE THREAD

**Issue by adilsaeed31** [judedaryl/nativescript-azure-auth#4]
Hi, 

I am trying to use this plugin in my project, unfortunately this plugin gives me an error while adding the object in the constructor with private var, 

```
ERROR NullInjectorError: StaticInjectorError(AppModule)[AppComponent -> AzureAuthenticationService]: 
JS:   StaticInjectorError(Platform: core)[AppComponent -> AzureAuthenticationService]: 
JS:     NullInjectorError: No provider for AzureAuthenticationService!
```

below line causing problem 
```
constructor( private azureAuthService: AzureAuthenticationService)
```
Please let me know what is the reason for that.

Thank you.

**Comment by adilsaeed31** [comment]
I fixed this issue, I have added below line in auth.service.ts file 

```
@Injectable({
    providedIn: "root"
})
```

**Comment by judedaryl** [comment]
@adilsaeed31 nice that you got it to work! and that it is still working.

I haven't been actively maintaining this repo, but i will be as soon as i reinstall nativescript.

If you have some suggestions / update feel free to give a pr!
